create table if not exists media_link (id bigint generated by default as identity, target_path varchar(255), link_path varchar(255), imdb_id varchar(255), the_movie_db_id integer not null, primary key (id), unique (target_path));

create table if not exists media_query (id bigint generated by default as identity, file_path varchar(255), primary key (id), unique (file_path));